<a href="https://colab.research.google.com/github/yuwaniyash/Sliit-AI-ML-course-tasks/blob/main/Sentiment-Analysis/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sentiment Analysis using NLP**

In [20]:
import pandas as pd
import nltk
nltk.download('punkt_tab')
import re

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [31]:
df = pd.read_csv('Tweets.csv',encoding='latin-1')
df.head(5)

(14640, 15)

In [35]:
df.groupby('airline_sentiment').describe()

                  tweet_id                                            \
                     count          mean           std           min
airline_sentiment
negative            9178.0  5.692602e+17  7.572474e+14  5.675900e+17
neutral             3099.0  5.691841e+17  8.068405e+14  5.675883e+17
positive            2363.0  5.691006e+17  8.112476e+14  5.676555e+17

                                                                           \
                            25%           50%           75%           max
airline_sentiment
negative           5.686511e+17  5.695355e+17  5.698798e+17  5.703106e+17
neutral            5.684852e+17  5.693080e+17  5.699305e+17  5.703093e+17
positive           5.684331e+17  5.691980e+17  5.698788e+17  5.703093e+17

                  airline_sentiment_confidence            ...  \
                                         count      mean  ...
airline_sentiment                                         ...
negative                                9178.0  0.933365  ...
neutral                                 3099.0  0.823303  ...
positive                                2363.0  0.872039  ...

                  negativereason_confidence      retweet_count            \
                                        75%  max         count      mean
airline_sentiment
negative                                1.0  1.0        9178.0  0.093375
neutral                                 0.0  0.0        3099.0  0.060987
positive                                0.0  0.0        2363.0  0.069403


                        std  min  25%  50%  75%   max
airline_sentiment
negative           0.792865  0.0  0.0  0.0  0.0  44.0
neutral            0.658037  0.0  0.0  0.0  0.0  28.0
positive           0.659914  0.0  0.0  0.0  0.0  22.0

[3 rows x 32 columns]

In [36]:
print(df[df['airline_sentiment'] == 'neutral']['text'].nunique())

3067

In [22]:
df = df[["airline_sentiment", "text"]]
df.head(5)

  airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [23]:
import string
from nltk.stem.porter import PorterStemmer


nltk.download('stopwords')
from nltk.corpus import stopwords

ps = PorterStemmer()

def clean_text(text):
  text = text.lower()
  text = re.sub(r'http.?://[^\s]+[\s]?', '', text)
  text = nltk.word_tokenize(text)

  y = []

  for i in text:
    if i not in stopwords.words('english'):
      y.append(i)
      text = y[:]

  y.clear()

  for i in text:
    y.append(ps.stem(i))

  return" ".join(y)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [33]:
df['text_cleaned'] = df['text'].apply(clean_text)
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,text_cleaned
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),@ virginamerica @ dhepburn said .
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),@ virginamerica plu 've ad commerci experi ......
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),@ virginamerica n't today ... must mean need t...
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),@ virginamerica 's realli aggress blast obnoxi...
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),@ virginamerica 's realli big bad thing

# Feature Extracting

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf_vec = TfidfVectorizer(max_features=3000)
X = tf_vec.fit_transform(df['text_cleaned']).toarray()

Y = df['airline_sentiment'].values

print(X.shape, Y.shape)

(14640, 3000) (14640,)

# Training Model

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=2
)

# Multinomial Naive Bayes

In [29]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))

Naive Bayes Accuracy: 0.7233606557377049

# Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))

Random Forest Accuracy: 0.7489754098360656